"""
AfPO Gap Reporter
Builds a pre-filled GitHub Issue URL for population/ethnicity values that
could not be matched in the African Population Ontology (AfPO).
"""
from __future__ import annotations
from urllib.parse import urlencode


def build_github_issue_url(unmatched_value: str, study_name: str, variable_name: str) -> str:
    """Generate a pre-filled GitHub Issue URL for an unmatched AfPO value."""
    title = f"New term request: {unmatched_value}"
    body = f"""## New AfPO Term Request

**Population/ethnicity value not found in AfPO:**
{unmatched_value}

**Encountered in study:**
{study_name}

**Mapped variable:**
{variable_name}

**Suggested parent group (if known):**
(please fill in — e.g. Bantu Eastern, Nilotic Eastern)

**References (if known):**
(Wikipedia link, ISO 639 code, etc.)

---
*This request was generated by the Metadata Harmonisation Tool.*
*AfPO contributing guide: https://github.com/h3abionet/afpo/blob/main/CONTRIBUTING.md*
"""
    params = {
        "title": title,
        "body": body,
        "labels": "new term",
    }
    base_url = "https://github.com/h3abionet/afpo/issues/new"
    return f"{base_url}?{urlencode(params)}"
